/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bellecosmetique;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Admin
 */
public class Home1 extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img_fundo = new javax.swing.JPanel();
        img_logofundo = new javax.swing.JLabel();
        btn_produtos = new javax.swing.JLabel();
        lb_pedidos = new javax.swing.JLabel();
        btn_pedidos = new javax.swing.JLabel();
        btn_fornecedores = new javax.swing.JLabel();
        btn_clientes = new javax.swing.JLabel();
        lb_produtos = new javax.swing.JLabel();
        lb_fornecedores = new javax.swing.JLabel();
        lb_clientes = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lb_fundopreto = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        icone_calendario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lb_data = new javax.swing.JLabel();
        lb_ultimoacesso = new javax.swing.JLabel();
        img_user = new javax.swing.JLabel();
        lb_cargo = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        lb_nome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img_fundo.setBackground(new java.awt.Color(255, 102, 102));
        img_fundo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img_logofundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_marcadagua-03.png"))); // NOI18N
        img_logofundo.setText("jLabel1");
        img_fundo.add(img_logofundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 250, 210));

        btn_produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_produtos-04.png"))); // NOI18N
        btn_produtos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_produtosMouseEntered(evt);
            }
        });
        img_fundo.add(btn_produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 160, 150));

        lb_pedidos.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lb_pedidos.setForeground(new java.awt.Color(255, 255, 255));
        lb_pedidos.setText("PEDIDOS");
        img_fundo.add(lb_pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, -1, -1));

        btn_pedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_pedidos_06-07.png"))); // NOI18N
        btn_pedidos.setText("jLabel6");
        img_fundo.add(btn_pedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 150, 150));

        btn_fornecedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_fornecedores-05.png"))); // NOI18N
        btn_fornecedores.setText("jLabel6");
        img_fundo.add(btn_fornecedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 150, 150));

        btn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icone_clientes-06-06.png"))); // NOI18N
        btn_clientes.setText("jLabel6");
        img_fundo.add(btn_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 150, 150));

        lb_produtos.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lb_produtos.setForeground(new java.awt.Color(255, 255, 255));
        lb_produtos.setText("PRODUTOS");
        img_fundo.add(lb_produtos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        lb_fornecedores.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lb_fornecedores.setForeground(new java.awt.Color(255, 255, 255));
        lb_fornecedores.setText("FORNECEDORES");
        img_fundo.add(lb_fornecedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, -1, -1));

        lb_clientes.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lb_clientes.setForeground(new java.awt.Color(255, 255, 255));
        lb_clientes.setText("CLIENTES");
        img_fundo.add(lb_clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 520, -1, -1));

        getContentPane().add(img_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 940, 650));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1240, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, -1));

        lb_fundopreto.setBackground(new java.awt.Color(53, 53, 53));

        jPanel4.setBackground(new java.awt.Color(61, 61, 61));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setForeground(new java.awt.Color(51, 51, 51));

        icone_calendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Calendar_25px.png"))); // NOI18N

        lb_data.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lb_data.setForeground(new java.awt.Color(255, 255, 255));
        lb_data.setText("Outubro 2018");

        lb_ultimoacesso.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lb_ultimoacesso.setForeground(new java.awt.Color(255, 255, 255));
        lb_ultimoacesso.setText("Último Acesso");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lb_ultimoacesso)
                        .addGap(47, 47, 47)
                        .addComponent(lb_data)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(icone_calendario)
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addGap(40, 40, 40))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(icone_calendario))
                    .addComponent(lb_data, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_ultimoacesso, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 62, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, -1, 130));

        img_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/imge_1.jpg"))); // NOI18N
        jPanel4.add(img_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 86, -1));

        lb_cargo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lb_cargo.setForeground(new java.awt.Color(255, 255, 255));
        lb_cargo.setText("Gerente");
        jPanel4.add(lb_cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 30));

        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/swing/images/icons8_Exit_25px.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_exitMousePressed(evt);
            }
        });
        jPanel4.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, 46));

        lb_nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb_nome.setForeground(new java.awt.Color(255, 255, 255));
        lb_nome.setText("Nome Sobrenome");
        jPanel4.add(lb_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, 30));

        javax.swing.GroupLayout lb_fundopretoLayout = new javax.swing.GroupLayout(lb_fundopreto);
        lb_fundopreto.setLayout(lb_fundopretoLayout);
        lb_fundopretoLayout.setHorizontalGroup(
            lb_fundopretoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
        );
        lb_fundopretoLayout.setVerticalGroup(
            lb_fundopretoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lb_fundopretoLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(435, Short.MAX_VALUE))
        );

        getContentPane().add(lb_fundopreto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 300, 650));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int xx,xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btn_exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMousePressed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_btn_exitMousePressed

    private void btn_produtosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_produtosMouseEntered

    }//GEN-LAST:event_btn_produtosMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home1().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_clientes;
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel btn_fornecedores;
    private javax.swing.JLabel btn_pedidos;
    private javax.swing.JLabel btn_produtos;
    private javax.swing.JLabel icone_calendario;
    private javax.swing.JPanel img_fundo;
    private javax.swing.JLabel img_logofundo;
    private javax.swing.JLabel img_user;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_cargo;
    private javax.swing.JLabel lb_clientes;
    private javax.swing.JLabel lb_data;
    private javax.swing.JLabel lb_fornecedores;
    private javax.swing.JPanel lb_fundopreto;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_pedidos;
    private javax.swing.JLabel lb_produtos;
    private javax.swing.JLabel lb_ultimoacesso;
    // End of variables declaration//GEN-END:variables

    private void setIconImage(String icone_produtos_sombra0404png) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
