/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Cursor;

/**
 *
 * @author Professor Rodolfo
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        img_logo1 = new javax.swing.JPanel();
        sp2_linha = new javax.swing.JPanel();
        btn_fechar = new javax.swing.JLabel();
        lb_usuario = new javax.swing.JLabel();
        input_senha = new javax.swing.JTextField();
        sp_linha1 = new javax.swing.JSeparator();
        lb_senha = new javax.swing.JLabel();
        sp3_linha = new javax.swing.JPasswordField();
        sp_linha3 = new javax.swing.JSeparator();
        btn_login = new javax.swing.JLabel();
        img_logo = new javax.swing.JLabel();
        img_logo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento - Belle Cosmétique");
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        img_logo1.setBackground(new java.awt.Color(255, 102, 102));
        img_logo1.setForeground(new java.awt.Color(255, 51, 153));
        img_logo1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                img_logo1MouseDragged(evt);
            }
        });
        img_logo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                img_logo1MousePressed(evt);
            }
        });

        sp2_linha.setBackground(new java.awt.Color(255, 255, 255));

        btn_fechar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_fechar.setForeground(new java.awt.Color(204, 204, 204));
        btn_fechar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_fechar.setText("X");
        btn_fechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_fecharMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_fecharMouseEntered(evt);
            }
        });

        lb_usuario.setBackground(new java.awt.Color(102, 102, 102));
        lb_usuario.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lb_usuario.setText("Usuário");

        input_senha.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        input_senha.setBorder(null);
        input_senha.setCaretColor(new java.awt.Color(255, 102, 102));
        input_senha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        input_senha.setOpaque(false);
        input_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_senhaActionPerformed(evt);
            }
        });

        lb_senha.setBackground(new java.awt.Color(102, 102, 102));
        lb_senha.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        lb_senha.setText("Senha");

        sp3_linha.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        sp3_linha.setBorder(null);
        sp3_linha.setCaretColor(new java.awt.Color(255, 102, 102));
        sp3_linha.setOpaque(false);
        sp3_linha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp3_linhaActionPerformed(evt);
            }
        });

        btn_login.setBackground(new java.awt.Color(255, 255, 255));
        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/btnLogin.png"))); // NOI18N

        javax.swing.GroupLayout sp2_linhaLayout = new javax.swing.GroupLayout(sp2_linha);
        sp2_linha.setLayout(sp2_linhaLayout);
        sp2_linhaLayout.setHorizontalGroup(
            sp2_linhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sp2_linhaLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(sp2_linhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sp2_linhaLayout.createSequentialGroup()
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sp2_linhaLayout.createSequentialGroup()
                        .addGroup(sp2_linhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sp2_linhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(input_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sp_linha1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sp3_linha, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sp_linha3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        sp2_linhaLayout.setVerticalGroup(
            sp2_linhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sp2_linhaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btn_fechar)
                .addGap(61, 61, 61)
                .addComponent(lb_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(input_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(sp_linha1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(sp2_linhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(sp2_linhaLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(sp3_linha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(sp_linha3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        img_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo_white_400x400-02.png"))); // NOI18N
        img_logo.setText("jLabel3");

        img_logo3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        img_logo3.setForeground(new java.awt.Color(255, 153, 153));
        img_logo3.setText("FATEC São José dos Campos - 2018");

        javax.swing.GroupLayout img_logo1Layout = new javax.swing.GroupLayout(img_logo1);
        img_logo1.setLayout(img_logo1Layout);
        img_logo1Layout.setHorizontalGroup(
            img_logo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, img_logo1Layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(img_logo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, img_logo1Layout.createSequentialGroup()
                        .addComponent(img_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, img_logo1Layout.createSequentialGroup()
                        .addComponent(img_logo3)
                        .addGap(154, 154, 154)))
                .addComponent(sp2_linha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        img_logo1Layout.setVerticalGroup(
            img_logo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp2_linha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(img_logo1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(img_logo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(img_logo3)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img_logo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(img_logo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_fecharMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fecharMouseEntered

    }//GEN-LAST:event_btn_fecharMouseEntered

    private void btn_fecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_fecharMouseClicked
        this.dispose();
    }//GEN-LAST:event_btn_fecharMouseClicked

    private void sp3_linhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp3_linhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sp3_linhaActionPerformed

int xx, xy;
    private void img_logo1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_logo1MousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_img_logo1MousePressed

    private void img_logo1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_img_logo1MouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_img_logo1MouseDragged

    private void input_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_senhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_senhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_fechar;
    private javax.swing.JLabel btn_login;
    private javax.swing.JLabel img_logo;
    private javax.swing.JPanel img_logo1;
    private javax.swing.JLabel img_logo3;
    private javax.swing.JTextField input_senha;
    private javax.swing.JLabel lb_senha;
    private javax.swing.JLabel lb_usuario;
    private javax.swing.JPanel sp2_linha;
    private javax.swing.JPasswordField sp3_linha;
    private javax.swing.JSeparator sp_linha1;
    private javax.swing.JSeparator sp_linha3;
    // End of variables declaration//GEN-END:variables
}
